function result = MRFUpsamplingEqO2(color,depth,sigma,lambda1,lambda2)
%Solve the large sparse linear system generated by the second order MRF upsamling model
%Output: 
%   result      -   the output depth data
%Input: 
%   color       -   Input color image
%   depth       -   Depth map need upsampling
%   sigma       -   Coefficient of gaussian kernel for color similarity
%   lambda1     -   The balance factor between data term and smoothness term
%   lambda2     -   The balance factor between data term and second order smoothness term
%Reference
%   Image and Sparse Laser Fusion for Dense Scene Reconstruction
%   Alastair Harrison and Paul Newman
%Code Author:
%   Liu Junyi, Zhejiang University
%   June 2012
%   Modified by Liu Junyi
%   Dec. 2012
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%For Debug
%     savefile = 'Debug_MRF_Upsampling.mat';
    
    height = size(color,1);
    width = size(color,2);
    pixelNumber = height * width;
    
    %Depth Matrix - N*1
    depth = double(depth);
    Z = sparse(reshape(depth,pixelNumber,1));
    
    %Data Term Matrix - N*N
    x = find(reshape(depth,pixelNumber,1)>0);
    y = x;
    s = 1;
    W = sparse(x,y,s,pixelNumber,pixelNumber);
    
    %Smoothness Term Matrix - 4N*N, Here we exclude the pixels on the boundary
    color = double(color);
    tic;
    S = ColorSmoothnessTerm(color,sigma);
%     save(savefile,'S','S2');
    R = ColorSecondSmoothnessTerm(color,sigma);
    SmoothnessTime = toc;
    fprintf('    The running time of generating the pairwise matrix is %.5f s\n',SmoothnessTime)
      
   
    %Compute the A and b
    tic; 
    A1 = S'*S;
    A2 = W'*W;
    A3 = R'*R;
    A = lambda1 * A1 + A2 + lambda2*A3;
    b = W'*W*Z;
    MatrixGenerateTime = toc;
    fprintf('    The running time of getting A and b is %.5f s\n',MatrixGenerateTime)
    
    %Using Backslash to solve the Ax=b
    tic;
    Result = A\b;
    BackslashTime = toc;
    fprintf('    The running time of solving Ax=b by Backslash is %.5f s\n',BackslashTime)
    
    result = full(reshape(double(Result),height,width));
    result(1) = result(2);
    result(height) = result(height-1);
    result(height*width - height + 1) = result(height*width - height + 2) ;
    result(height*width) = result(height*width-1);
    fprintf('    Done!\n')
end